name: blog-image-gen
region: sfo
services:
- name: generator-api
  github:
    repo: alston808/blog-image-gen
    branch: main
  instance_size_slug: basic-xs
  instance_count: 1
  build_command: pip install -r requirements.txt
  run_command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:8080  http_port: 8080
  health_check:
    path: /health
  env:
    - key: DO_API_TOKEN
      scope: RUN_TIME
      value: ${DO_API_TOKEN}
    - key: CLI_TOKEN
      scope: RUN_TIME
      value: ${CLI_TOKEN}
